### ISSUE TITLE
unspecified runtime dependency onto sequel

### ISSUE THREAD

**Issue by mmoll** [Dynflow/dynflow#172]
sequel is specified as development dependency, but the following is happening, when loading dynflow without sequel being installed:
```
irb(main):001:0> require 'dynflow'
LoadError: cannot load such file -- sequel/no_core_ext
	from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/vendor_ruby/dynflow/persistence_adapters/sequel.rb:1:in `<top (required)>'
	from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/vendor_ruby/dynflow/persistence_adapters.rb:4:in `<module:PersistenceAdapters>'
	from /usr/lib/ruby/vendor_ruby/dynflow/persistence_adapters.rb:2:in `<module:Dynflow>'
	from /usr/lib/ruby/vendor_ruby/dynflow/persistence_adapters.rb:1:in `<top (required)>'
	from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/vendor_ruby/dynflow/persistence.rb:1:in `<top (required)>'
	from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/vendor_ruby/dynflow.rb:34:in `<module:Dynflow>'
	from /usr/lib/ruby/vendor_ruby/dynflow.rb:19:in `<top (required)>'
	from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from (irb):1
	from /usr/bin/irb:11:in `<main>'irb(main):002:0> 
```

**Comment by iNecas** [comment]
Fixed in https://github.com/Dynflow/dynflow/commit/a9655bfd9d3fb7b6629fd239219b52eda9205c14
