### ISSUE TITLE
warnings when booting app with sidekiq 6.5.x

### ISSUE THREAD

**Issue by evgeni** [Dynflow/dynflow#431]
Ohai,

we've recently upgraded Foreman to use sidekiq 6.5.x, and now when we boot the app the following warnings are logged:

```
Oct 19 06:31:08 centos8-stream-foreman-nightly.tanso.example.com foreman[1267]: 2023-10-19T06:31:08.167Z pid=1267 tid=33b WARN: `config.options[:key] = value` is deprecated, use `config[:key] = value`: ["/usr/share/gems/gems/dynflow-1.8.0/lib/dynflow/rails/configuration.rb:103:in `sidekiq_worker?'", "/usr/share/gems/gems/dynflow-1.8.0/lib/dynflow/rails/configuration.rb:155:in `block in world_config'"]
Oct 19 06:31:08 centos8-stream-foreman-nightly.tanso.example.com foreman[1268]: 2023-10-19T06:31:08.171Z pid=1268 tid=334 WARN: `config.options[:key] = value` is deprecated, use `config[:key] = value`: ["/usr/share/gems/gems/dynflow-1.8.0/lib/dynflow/rails/configuration.rb:103:in `sidekiq_worker?'", "/usr/share/gems/gems/dynflow-1.8.0/lib/dynflow/rails/configuration.rb:155:in `block in world_config'"]
Oct 19 06:31:08 centos8-stream-foreman-nightly.tanso.example.com foreman[1266]: 2023-10-19T06:31:08.174Z pid=1266 tid=33a WARN: `config.options[:key] = value` is deprecated, use `config[:key] = value`: ["/usr/share/gems/gems/dynflow-1.8.0/lib/dynflow/rails/configuration.rb:103:in `sidekiq_worker?'", "/usr/share/gems/gems/dynflow-1.8.0/lib/dynflow/rails/configuration.rb:155:in `block in world_config'"]
Oct 19 06:31:08 centos8-stream-foreman-nightly.tanso.example.com foreman[1266]: 2023-10-19T06:31:08.206Z pid=1266 tid=33a WARN: `config.options[:key] = value` is deprecated, use `config[:key] = value`: ["/usr/share/gems/gems/dynflow-1.8.0/lib/dynflow/rails/configuration.rb:103:in `sidekiq_worker?'", "/usr/share/gems/gems/dynflow-1.8.0/lib/dynflow/rails/configuration.rb:99:in `increase_db_pool_size?'"]
Oct 19 06:31:08 centos8-stream-foreman-nightly.tanso.example.com foreman[1267]: 2023-10-19T06:31:08.211Z pid=1267 tid=33b WARN: `config.options[:key] = value` is deprecated, use `config[:key] = value`: ["/usr/share/gems/gems/dynflow-1.8.0/lib/dynflow/rails/configuration.rb:103:in `sidekiq_worker?'", "/usr/share/gems/gems/dynflow-1.8.0/lib/dynflow/rails/configuration.rb:99:in `increase_db_pool_size?'"]
Oct 19 06:31:08 centos8-stream-foreman-nightly.tanso.example.com foreman[1268]: 2023-10-19T06:31:08.233Z pid=1268 tid=334 WARN: `config.options[:key] = value` is deprecated, use `config[:key] = value`: ["/usr/share/gems/gems/dynflow-1.8.0/lib/dynflow/rails/configuration.rb:103:in `sidekiq_worker?'", "/usr/share/gems/gems/dynflow-1.8.0/lib/dynflow/rails/configuration.rb:99:in `increase_db_pool_size?'"]
Oct 19 06:31:08 centos8-stream-foreman-nightly.tanso.example.com foreman[1266]: 2023-10-19T06:31:08.400Z pid=1266 tid=33a WARN: `config.options[:key] = value` is deprecated, use `config[:key] = value`: ["/usr/share/gems/gems/dynflow-1.8.0/lib/dynflow/rails/configuration.rb:103:in `sidekiq_worker?'", "/usr/share/gems/gems/dynflow-1.8.0/lib/dynflow/rails/configuration.rb:99:in `increase_db_pool_size?'"]
Oct 19 06:31:08 centos8-stream-foreman-nightly.tanso.example.com foreman[1268]: 2023-10-19T06:31:08.506Z pid=1268 tid=334 WARN: `config.options[:key] = value` is deprecated, use `config[:key] = value`: ["/usr/share/gems/gems/dynflow-1.8.0/lib/dynflow/rails/configuration.rb:103:in `sidekiq_worker?'", "/usr/share/gems/gems/dynflow-1.8.0/lib/dynflow/rails/configuration.rb:99:in `increase_db_pool_size?'"]
Oct 19 06:31:08 centos8-stream-foreman-nightly.tanso.example.com foreman[1267]: 2023-10-19T06:31:08.571Z pid=1267 tid=33b WARN: `config.options[:key] = value` is deprecated, use `config[:key] = value`: ["/usr/share/gems/gems/dynflow-1.8.0/lib/dynflow/rails/configuration.rb:103:in `sidekiq_worker?'", "/usr/share/gems/gems/dynflow-1.8.0/lib/dynflow/rails/configuration.rb:99:in `increase_db_pool_size?'"]
```

**Comment by evgeni** [comment]
See https://github.com/sidekiq/sidekiq/commit/67daa7a408b214d593100f782271ed108686c147 for details
